spring:
  kafka:
    producer:
      bootstrap-servers: "NONE"
      topic: NONE
    consumer:
      bootstrap-servers: "NONE"
      topic: NONE
      group-id: streaming-platform-e2e
      concurrency: 1
